spring:
  datasource:
    url: jdbc:mysql://10.0.0.242:3306/ifdp?autoReconnect=true&useSSL=true
    username: ifdp
    password: $ifdp@2017
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379

security:
  basic:
    enabled : false

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug
    com.omcube: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml

---
spring:
  profiles: production
  redis:
    host: r-wz9aee93374e6f44.redis.rds.aliyuncs.com
    password: Ifdp2017
