server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://10.0.0.242:3306/ifdp?autoReconnect=true&useSSL=true&characterEncoding=UTF-8
    username: ifdp
    password: $ifdp@2017
    type: com.alibaba.druid.pool.DruidDataSource
    logSlowSql: true
    druid:
      web-stat-filter:
        enabled: false
    
  redis:
    host: 10.0.0.242
    port: 6379
    password: $ifdp@2017
    

security:
  basic:
    enabled : false

logging:
  file: log/ifdp-web.log
  level:
    org.springframework.web: debug
    org.springframework.security: debug
    com.omcube: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml

---
spring:
  profiles: production
  redis:
    host: r-wz9aee93374e6f44.redis.rds.aliyuncs.com
    password: Ifdp2017
